// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/feature/profile/data/repository_imp/profile_screen_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:tracking_app/core/common/result.dart' as _i5;
import 'package:tracking_app/feature/profile/data/data_source/profile_local_data_source.dart'
    as _i10;
import 'package:tracking_app/feature/profile/data/data_source/profile_remote_data_source.dart'
    as _i3;
import 'package:tracking_app/feature/profile/data/model/change_password_request_model.dart'
    as _i9;
import 'package:tracking_app/feature/profile/data/model/profile_response_dto.dart'
    as _i2;
import 'package:tracking_app/feature/profile/domain/entity/change_password_entity.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileResponseDTO_0 extends _i1.SmartFake
    implements _i2.ProfileResponseDTO {
  _FakeProfileResponseDTO_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSource extends _i1.Mock
    implements _i3.ProfileRemoteDataSource {
  MockProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ProfileResponseDTO> getProfileData() => (super.noSuchMethod(
        Invocation.method(
          #getProfileData,
          [],
        ),
        returnValue:
            _i4.Future<_i2.ProfileResponseDTO>.value(_FakeProfileResponseDTO_0(
          this,
          Invocation.method(
            #getProfileData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ProfileResponseDTO>);

  @override
  _i4.Future<_i2.ProfileResponseDTO> editProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [data],
        ),
        returnValue:
            _i4.Future<_i2.ProfileResponseDTO>.value(_FakeProfileResponseDTO_0(
          this,
          Invocation.method(
            #editProfile,
            [data],
          ),
        )),
      ) as _i4.Future<_i2.ProfileResponseDTO>);

  @override
  _i4.Future<_i5.Result<String?>> uploadPhoto(_i6.File? photo) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [photo],
        ),
        returnValue: _i4.Future<_i5.Result<String?>>.value(
            _i7.dummyValue<_i5.Result<String?>>(
          this,
          Invocation.method(
            #uploadPhoto,
            [photo],
          ),
        )),
      ) as _i4.Future<_i5.Result<String?>>);

  @override
  _i4.Future<_i5.Result<_i8.ChangePasswordEntity>> changePassword(
          _i9.ChangePasswordRequestModel? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [data],
        ),
        returnValue: _i4.Future<_i5.Result<_i8.ChangePasswordEntity>>.value(
            _i7.dummyValue<_i5.Result<_i8.ChangePasswordEntity>>(
          this,
          Invocation.method(
            #changePassword,
            [data],
          ),
        )),
      ) as _i4.Future<_i5.Result<_i8.ChangePasswordEntity>>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ProfileLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileLocalDataSource extends _i1.Mock
    implements _i10.ProfileLocalDataSource {
  MockProfileLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> cacheToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #cacheToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
