// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/feature/auth/data/data_source/auth_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tracking_app/core/api/api_client.dart' as _i6;
import 'package:tracking_app/feature/auth/data/model/forget_response_password_dto.dart'
    as _i3;
import 'package:tracking_app/feature/auth/data/model/reset_password_dto.dart'
    as _i5;
import 'package:tracking_app/feature/auth/data/model/sign_in_response_dto.dart'
    as _i2;
import 'package:tracking_app/feature/auth/data/model/verify_email_response_dto.dart'
    as _i4;
import 'package:tracking_app/feature/auth/domain/entity/sign_in_request.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignInResponseDTO_0 extends _i1.SmartFake
    implements _i2.SignInResponseDTO {
  _FakeSignInResponseDTO_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForgetResponsePasswordDto_1 extends _i1.SmartFake
    implements _i3.ForgetResponsePasswordDto {
  _FakeForgetResponsePasswordDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyEmailResponseDto_2 extends _i1.SmartFake
    implements _i4.VerifyEmailResponseDto {
  _FakeVerifyEmailResponseDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResponseDTO_3 extends _i1.SmartFake
    implements _i5.ResetPasswordResponseDTO {
  _FakeResetPasswordResponseDTO_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i6.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.SignInResponseDTO> signIn(_i8.SignInRequest? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [data],
        ),
        returnValue:
            _i7.Future<_i2.SignInResponseDTO>.value(_FakeSignInResponseDTO_0(
          this,
          Invocation.method(
            #signIn,
            [data],
          ),
        )),
      ) as _i7.Future<_i2.SignInResponseDTO>);

  @override
  _i7.Future<_i3.ForgetResponsePasswordDto> forgetPassword(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [data],
        ),
        returnValue: _i7.Future<_i3.ForgetResponsePasswordDto>.value(
            _FakeForgetResponsePasswordDto_1(
          this,
          Invocation.method(
            #forgetPassword,
            [data],
          ),
        )),
      ) as _i7.Future<_i3.ForgetResponsePasswordDto>);

  @override
  _i7.Future<_i4.VerifyEmailResponseDto> verifyEmail(
          Map<String, String>? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [code],
        ),
        returnValue: _i7.Future<_i4.VerifyEmailResponseDto>.value(
            _FakeVerifyEmailResponseDto_2(
          this,
          Invocation.method(
            #verifyEmail,
            [code],
          ),
        )),
      ) as _i7.Future<_i4.VerifyEmailResponseDto>);

  @override
  _i7.Future<_i5.ResetPasswordResponseDTO> resetPassword(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [data],
        ),
        returnValue: _i7.Future<_i5.ResetPasswordResponseDTO>.value(
            _FakeResetPasswordResponseDTO_3(
          this,
          Invocation.method(
            #resetPassword,
            [data],
          ),
        )),
      ) as _i7.Future<_i5.ResetPasswordResponseDTO>);
}
