// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/feature/auth/data/data_source/auth_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/dio.dart' as _i2;
import 'package:tracking_app/core/api/api_client.dart' as _i7;
import 'package:tracking_app/feature/apply/data/model/apply_response_dto.dart'
    as _i9;
import 'package:tracking_app/feature/apply/data/model/get_vehicles_response_dto.dart'
    as _i12;
import 'package:tracking_app/feature/auth/data/model/forget_response_password_dto.dart'
    as _i4;
import 'package:tracking_app/feature/auth/data/model/reset_password_dto.dart'
    as _i6;
import 'package:tracking_app/feature/auth/data/model/sign_in_response_dto.dart'
    as _i3;
import 'package:tracking_app/feature/auth/data/model/verify_email_response_dto.dart'
    as _i5;
import 'package:tracking_app/feature/auth/domain/entity/sign_in_request.dart'
    as _i11;
import 'package:tracking_app/feature/home/data/model/pending_orders_response_dto.dart'
    as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignInResponseDTO_1 extends _i1.SmartFake
    implements _i3.SignInResponseDTO {
  _FakeSignInResponseDTO_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForgetResponsePasswordDto_2 extends _i1.SmartFake
    implements _i4.ForgetResponsePasswordDto {
  _FakeForgetResponsePasswordDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyEmailResponseDto_3 extends _i1.SmartFake
    implements _i5.VerifyEmailResponseDto {
  _FakeVerifyEmailResponseDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResponseDTO_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponseDTO {
  _FakeResetPasswordResponseDTO_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i7.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.HttpResponse<_i9.ApplyResponseDTO>> apply(
    String? country,
    String? firstName,
    String? lastName,
    String? vehicleType,
    String? vehicleNumber,
    _i10.File? vehicleLicense,
    String? NID,
    _i10.File? NIDImg,
    String? email,
    String? password,
    String? rePassword,
    String? gender,
    String? phone,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #apply,
          [
            country,
            firstName,
            lastName,
            vehicleType,
            vehicleNumber,
            vehicleLicense,
            NID,
            NIDImg,
            email,
            password,
            rePassword,
            gender,
            phone,
          ],
        ),
        returnValue: _i8.Future<_i2.HttpResponse<_i9.ApplyResponseDTO>>.value(
            _FakeHttpResponse_0<_i9.ApplyResponseDTO>(
          this,
          Invocation.method(
            #apply,
            [
              country,
              firstName,
              lastName,
              vehicleType,
              vehicleNumber,
              vehicleLicense,
              NID,
              NIDImg,
              email,
              password,
              rePassword,
              gender,
              phone,
            ],
          ),
        )),
      ) as _i8.Future<_i2.HttpResponse<_i9.ApplyResponseDTO>>);

  @override
  _i8.Future<_i3.SignInResponseDTO> signIn(_i11.SignInRequest? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [data],
        ),
        returnValue:
            _i8.Future<_i3.SignInResponseDTO>.value(_FakeSignInResponseDTO_1(
          this,
          Invocation.method(
            #signIn,
            [data],
          ),
        )),
      ) as _i8.Future<_i3.SignInResponseDTO>);

  @override
  _i8.Future<_i4.ForgetResponsePasswordDto> forgetPassword(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [data],
        ),
        returnValue: _i8.Future<_i4.ForgetResponsePasswordDto>.value(
            _FakeForgetResponsePasswordDto_2(
          this,
          Invocation.method(
            #forgetPassword,
            [data],
          ),
        )),
      ) as _i8.Future<_i4.ForgetResponsePasswordDto>);

  @override
  _i8.Future<_i5.VerifyEmailResponseDto> verifyEmail(
          Map<String, String>? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [code],
        ),
        returnValue: _i8.Future<_i5.VerifyEmailResponseDto>.value(
            _FakeVerifyEmailResponseDto_3(
          this,
          Invocation.method(
            #verifyEmail,
            [code],
          ),
        )),
      ) as _i8.Future<_i5.VerifyEmailResponseDto>);

  @override
  _i8.Future<_i6.ResetPasswordResponseDTO> resetPassword(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [data],
        ),
        returnValue: _i8.Future<_i6.ResetPasswordResponseDTO>.value(
            _FakeResetPasswordResponseDTO_4(
          this,
          Invocation.method(
            #resetPassword,
            [data],
          ),
        )),
      ) as _i8.Future<_i6.ResetPasswordResponseDTO>);

  @override
  _i8.Future<_i2.HttpResponse<_i12.GetVehiclesResponseDTO>> getAllVehicles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllVehicles,
          [],
        ),
        returnValue:
            _i8.Future<_i2.HttpResponse<_i12.GetVehiclesResponseDTO>>.value(
                _FakeHttpResponse_0<_i12.GetVehiclesResponseDTO>(
          this,
          Invocation.method(
            #getAllVehicles,
            [],
          ),
        )),
      ) as _i8.Future<_i2.HttpResponse<_i12.GetVehiclesResponseDTO>>);

  @override
  _i8.Future<void> updateOrderState(
    String? orderId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderState,
          [
            orderId,
            data,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i2.HttpResponse<_i13.PendingOrdersResponseDTO>>
      getPendingOrders() => (super.noSuchMethod(
            Invocation.method(
              #getPendingOrders,
              [],
            ),
            returnValue: _i8
                .Future<_i2.HttpResponse<_i13.PendingOrdersResponseDTO>>.value(
                _FakeHttpResponse_0<_i13.PendingOrdersResponseDTO>(
              this,
              Invocation.method(
                #getPendingOrders,
                [],
              ),
            )),
          ) as _i8.Future<_i2.HttpResponse<_i13.PendingOrdersResponseDTO>>);
}
