// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/feature/profile/domain/use_case/edit_profile_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tracking_app/core/common/result.dart' as _i4;
import 'package:tracking_app/feature/profile/data/model/change_password_request_model.dart'
    as _i9;
import 'package:tracking_app/feature/profile/domain/entity/change_password_entity.dart'
    as _i8;
import 'package:tracking_app/feature/profile/domain/entity/profile_response_entity.dart'
    as _i5;
import 'package:tracking_app/feature/profile/domain/repository/profile_screen_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i2.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.ProfileResponseEntity>> getProfileData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileData,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.ProfileResponseEntity>>.value(
            _i6.dummyValue<_i4.Result<_i5.ProfileResponseEntity>>(
          this,
          Invocation.method(
            #getProfileData,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.ProfileResponseEntity>>);

  @override
  _i3.Future<_i4.Result<_i5.ProfileResponseEntity>> editProfile(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [data],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.ProfileResponseEntity>>.value(
            _i6.dummyValue<_i4.Result<_i5.ProfileResponseEntity>>(
          this,
          Invocation.method(
            #editProfile,
            [data],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.ProfileResponseEntity>>);

  @override
  _i3.Future<_i4.Result<String?>> uploadPhoto(_i7.File? photo) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [photo],
        ),
        returnValue: _i3.Future<_i4.Result<String?>>.value(
            _i6.dummyValue<_i4.Result<String?>>(
          this,
          Invocation.method(
            #uploadPhoto,
            [photo],
          ),
        )),
      ) as _i3.Future<_i4.Result<String?>>);

  @override
  _i3.Future<_i4.Result<void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.Result<_i8.ChangePasswordEntity>> changePassword(
          _i9.ChangePasswordRequestModel? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [data],
        ),
        returnValue: _i3.Future<_i4.Result<_i8.ChangePasswordEntity>>.value(
            _i6.dummyValue<_i4.Result<_i8.ChangePasswordEntity>>(
          this,
          Invocation.method(
            #changePassword,
            [data],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i8.ChangePasswordEntity>>);
}
