// Mocks generated by Mockito 5.4.5 from annotations
// in tracking_app/test/feature/order_details/presentation/cubit/update_order_state_cubit/update_order_state_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:tracking_app/core/common/result.dart' as _i4;
import 'package:tracking_app/feature/order_details/domain/repository/update_order_state_repo.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UpdateOrderStateRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateOrderStateRepo extends _i1.Mock
    implements _i2.UpdateOrderStateRepo {
  MockUpdateOrderStateRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void>> updateOrderState(
    String? orderId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderState, [orderId, data]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i5.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateOrderState, [orderId, data]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
